// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpx0hx6-SzXBkecG49Lh2ull8_5QYSvfk',
    appId: '1:653621442056:web:ec0a6d8f5cb8da605ac3bd',
    messagingSenderId: '653621442056',
    projectId: 'nsbm-shuttle-app-desandu',
    authDomain: 'nsbm-shuttle-app-desandu.firebaseapp.com',
    storageBucket: 'nsbm-shuttle-app-desandu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQsRPHK1RL21dAVwQgY6dLH7VU5BmYYI',
    appId: '1:653621442056:android:a201893f16192cdb5ac3bd',
    messagingSenderId: '653621442056',
    projectId: 'nsbm-shuttle-app-desandu',
    storageBucket: 'nsbm-shuttle-app-desandu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGMxZpcpWe4UiyndQTpH3X3ridd7HwnM',
    appId: '1:653621442056:ios:f5d062f751059e5b5ac3bd',
    messagingSenderId: '653621442056',
    projectId: 'nsbm-shuttle-app-desandu',
    storageBucket: 'nsbm-shuttle-app-desandu.firebasestorage.app',
    iosBundleId: 'com.example.nsbmShuttle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEGMxZpcpWe4UiyndQTpH3X3ridd7HwnM',
    appId: '1:653621442056:ios:f5d062f751059e5b5ac3bd',
    messagingSenderId: '653621442056',
    projectId: 'nsbm-shuttle-app-desandu',
    storageBucket: 'nsbm-shuttle-app-desandu.firebasestorage.app',
    iosBundleId: 'com.example.nsbmShuttle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpx0hx6-SzXBkecG49Lh2ull8_5QYSvfk',
    appId: '1:653621442056:web:650d34ec68142d565ac3bd',
    messagingSenderId: '653621442056',
    projectId: 'nsbm-shuttle-app-desandu',
    authDomain: 'nsbm-shuttle-app-desandu.firebaseapp.com',
    storageBucket: 'nsbm-shuttle-app-desandu.firebasestorage.app',
  );
}
